### ISSUE TITLE
Can't serve locally...

### ISSUE THREAD

**Issue by joewheaton** [Restoration-USU/WATS-5340-5350#6]
Hi @philipbaileynar,
So, I am doing the COVID-19 thing and moving all my course content for rest of semester fully online. I've used the [instructions for serving locally](https://riverscapes.xyz/Tools/Technical_Reference/Documentation_Standards/WebSites/testing_locally.html#serving-a-site-locally) on both this site previously (maybe 2 months ago) and _currently_ on other sites (e.g. PBR).  

I tried serving this one locally on two different machines, and even tried re downloading the repo fresh. Both times I get the following:

```
C:\0_GIT\Riverscapes\WATS-5340-5350>bundle exec jekyll serve --trace
Configuration file: C:/0_GIT/Riverscapes/WATS-5340-5350/_config.yml
            Source: C:/0_GIT/Riverscapes/WATS-5340-5350
       Destination: C:/0_GIT/Riverscapes/WATS-5340-5350/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
      Remote Theme: Using theme riverscapes/riverscapes-jekyll-theme
Traceback (most recent call last):
        23: from C:/Ruby25-x64/bin/jekyll:23:in `<main>'
        22: from C:/Ruby25-x64/bin/jekyll:23:in `load'
        21: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
        20: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        19: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        18: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        17: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        16: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        15: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        14: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
        13: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
        12: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
        11: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:36:in `process'
        10: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:65:in `build'
         9: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:28:in `process_site'
         8: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:73:in `process'
         7: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:114:in `reset'
         6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/hooks.rb:101:in `trigger'
         5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/hooks.rb:101:in `each'
         4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/hooks.rb:102:in `block in trigger'
         3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-remote-theme-0.4.1/lib/jekyll-remote-theme.rb:33:in `block in <top (required)>'
         2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-remote-theme-0.4.1/lib/jekyll-remote-theme.rb:27:in `init'
         1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-remote-theme-0.4.1/lib/jekyll-remote-theme/munger.rb:26:in `munge!'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-remote-theme-0.4.1/lib/jekyll-remote-theme/munger.rb:55:in `configure_theme': undefined method `configure_sass' for #<Jekyll::RemoteTheme::Theme:0x000000000471f080> (NoMethodError)
```

It seems like that sass error I've been getting elsewhere but it is just a warning that I can push past. Any thoughts for what to do? Sorry to have such lame questions...

Thanks,
Joe

**Comment by joewheaton** [comment]
Updated from ruby 2.5.0 to [2.6.0](https://rubyinstaller.org/downloads/) using installer, and then reinstalling bundler (i.e. `gem install bundler:2.0.2`).

Then tried again at `C:\0_GIT\Riverscapes\WATS-5340-5350>` running `bundle exec jekyll serve --trace`

No go... same message as before:

> undefined method `configure_sass' for #<Jekyll::RemoteTheme::Theme:0x000000000471f080> (NoMethodError)

**Comment by joewheaton** [comment]
Decided to try:
- MSYS2 system update for ruby installer with `ridk install`
- Then closed shell
- Then `bundle exec jekyll serve --trace`

Same result. Hmm. 

Wanted to make sure I didn't break my ability to locally serve other repos. So tried in `C:\0_GIT\Riverscapes\PBR>bundle exec jekyll serve --trace` and got:

> Could not find i18n-0.9.5 in any of the sources
Run `bundle install` to install missing gems.

So ran `bundle install`

Tried again, and was able to serve LTPBR repo.

Thought  I would test in `C:\0_GIT\Riverscapes\pyBRAT\doc>bundle exec jekyll serve --trace` and it worked.

So, I'm confused why I can serve the [PBR repo](https://github.com/riverscapes/PBR) locally, and the [pyBRAT](https://github.com/riverscapes/pyBRAT) but not [WATS-5340-5350](https://github.com/Restoration-USU/WATS-5340-5350)?

**Comment by joewheaton** [comment]
Noticed that [Gemfile](https://github.com/Restoration-USU/WATS-5340-5350/blob/master/Gemfile) was six months old here, and in [PBR repo](https://github.com/Riverscapes/PBR/blob/master/Gemfile) was 4 months old. So I copied it in and:
- First attempted: `C:\0_GIT\Riverscapes\WATS-5340-5350>bundle exec jekyll serve` and got:

> You have requested:
>   jekyll = 3.8.6
> 
> The bundle currently has jekyll locked at 4.0.0.
> Try running `bundle update jekyll`
> 
> If you are updating multiple gems in your Gemfile at once,
> try passing them all to `bundle update`
> Run `bundle install` to install missing gems.
> 

So then `C:\0_GIT\Riverscapes\WATS-5340-5350>bundle update jekyll` and then yay! was able to run `C:\0_GIT\Riverscapes\WATS-5340-5350>bundle exec jekyll serve`
